export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";

export const GET_POPULAR_VIDEOS_START = "GET_POPULAR_VIDEOS_START";
export const GET_POPULAR_VIDEOS_SUCCESS = "GET_POPULAR_VIDEOS_SUCCESS";
export const GET_POPULAR_VIDEOS_FAIL = "GET_POPULAR_VIDEOS_FAIL";

export const GET_RELATED_VIDEOS_START = "GET_RELATED_VIDEOS_START";
export const GET_RELATED_VIDEOS_SUCCESS = "GET_RELATED_VIDEOS_SUCCESS";
export const GET_RELATED_VIDEOS_FAIL = "GET_RELATED_VIDEOS_FAIL";

export const GET_SEARCHED_VIDEOS_START = "GET_SEARCHED_VIDEOS_START";
export const GET_SEARCHED_VIDEOS_SUCCESS = "GET_SEARCHED_VIDEOS_SUCCESS";
export const GET_SEARCHED_VIDEOS_FAIL = "GET_SEARCHED_VIDEOS_FAIL";


export const GET_VIDEO_BY_ID_START = "GET_VIDEO_BY_ID_START";
export const GET_VIDEO_BY_ID_SUCCESS = "GET_VIDEO_BY_ID_SUCCESS";
export const GET_VIDEO_BY_ID_FAIL = "GET_POPULAR_VIDEOS_FAIL";

export const GET_CHANNEL_BY_ID_START = "GET_CHANNEL_BY_ID_START";
export const GET_CHANNEL_BY_ID_SUCCESS = "GET_CHANNEL_BY_ID_SUCCESS";
export const GET_CHANNEL_BY_ID_FAIL = "GET_CHANNEL_BY_ID_FAIL";

export const GET_COMMENTS_START = "GET_COMMENTS_START";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";